<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="AMOJAGTA-3D084" ignored="1" name="Default test(failed)" tests="2" failures="1" timestamp="28 Sep 2020 11:41:44 GMT" time="0.097" errors="0">
  <testcase name="Test3" time="0.022" classname="demo.TestNGRetryFailedDemo">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at demo.TestNGRetryFailedDemo.Test3(TestNGRetryFailedDemo.java:22)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- Test3 -->
  <testcase name="Test2" time="0.007" classname="demo.TestNGRetryFailedDemo"/>
  <testcase name="Test1" time="0.0" classname="demo.TestNGRetryFailedDemo">
    <ignored/>
  </testcase> <!-- Test1 -->
</testsuite> <!-- Default test(failed) -->
